language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - pytest --black --mypy --mypy-ignore-missing-imports --cov=src/pms --cov-report=term-missing --cov-fail-under=80