[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
dist-name = "PyPMS"
module = "pms"
author = "Alvaro Valdebenito"
author-email = "avaldebe@gmail.com"
home-page = "https://github.com/avaldebe/PyPMS"
requires = [
    "pyserial>=3.0",
    "paho-mqtt>=1.4.0",
    "influxdb>=5.2.0",
    "mypy-extensions>=0.4.0",
    "click>=7.0",
    'dataclasses;python_version=="3.6"',
]
requires-python = ">=3.6"
description-file = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Terminals :: Serial",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=5.0.0",
    "pytest-cov >=2.8.0",
    "pytest-black >=0.3.7",
    "pytest-mypy >=0.4.2",
]

[tool.flit.scripts]
pms = "pms.cli:main"

[tool.flit.sdist]
exclude = ["docs", "tests", ".gitignore", ".vscode", ".travis.yml"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38
skip_missing_interpreters = True
isolated_build = True

[testenv]
commands =
    py36: pytest --black --mypy --mypy-ignore-missing-imports
    py37: pytest --cov=pms --cov-report=term-missing --cov-fail-under=70
    py38: pytest
deps =
    pytest
    py36: pytest-black
    py36: pytest-mypy
    py37: pytest-cov
"""

[tool.black]
line-length = 100
target-version = ['py36']

