[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pypms"
version = "0.1.6"
description = "Data acquisition and logging tool for PM sensors with UART interface"
authors = ["Alvaro Valdebenito <avaldebe@gmail.com>"]
readme = "README.md"
repository = "https://github.com/avaldebe/PyPMS"
keywords = ["air quality", "particulate matter"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Terminals :: Serial",
    "Topic :: Utilities",
    "Typing :: Typed",
]
packages = [
    { include = "pms", from = "src"},
]
exclude = ["docs", "tests", ".gitignore", ".vscode", ".travis.yml"]


[tool.poetry.dependencies]
python = ">=3.6"
pyserial = ">=3.0"
mypy-extensions = ">=0.4.0"
click = ">=7.0"
dataclasses = { version = ">=0.6", python = "^3.6" }
paho-mqtt = { version = ">=1.4.0", optional = false}
influxdb = { version = ">=5.2.0", optional = false}

[tool.poetry.extras]
#service = ["paho-mqtt", "influxdb"]

[tool.poetry.dev-dependencies]
black = ">=20.8b1"
pytest = ">=5.0.0"
pytest-cov = ">=2.8.0"
pytest-black = ">=0.3.7"
pytest-mypy = ">=0.4.2"

[tool.poetry.scripts]
pms = "pms.cli:main"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38
skip_missing_interpreters = True
isolated_build = True

[testenv]
commands =
    py36: pytest --black --mypy --mypy-ignore-missing-imports
    py37: pytest --cov={envsitepackagesdir}/pms --cov-report=term-missing --cov-fail-under=70
    py38: pytest
deps =
    pytest
    py36: pytest-black
    py36: pytest-mypy
    py37: pytest-cov
"""

[tool.black]
line-length = 100
target-version = ['py36']
